In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/instructions/kagglepca.ipynb
/kaggle/input/heart-disease-uab/heart.csv


In [2]:
df1 =  pd.read_csv('/kaggle/input/heart-disease-uab/heart.csv')

In [3]:
print(df1)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2     

In [4]:
print(df1.shape)
print(df1.columns)
print(df1.index)
print(df1.head(5))

(303, 14)
Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')
RangeIndex(start=0, stop=303, step=1)
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  


In [5]:
matriz_1=np.genfromtxt('/kaggle/input/heart-disease-uab/heart.csv',delimiter=',', skip_header=1)
matriz_2 = matriz_1[:,[3,4,5,7]]
print(matriz_2)

[[145. 233.   1. 150.]
 [130. 250.   0. 187.]
 [130. 204.   0. 172.]
 ...
 [144. 193.   1. 141.]
 [130. 131.   0. 115.]
 [130. 236.   0. 174.]]


In [6]:
matriz_2m=np.mean(matriz_2, 0)
matriz_2sd=np.sqrt(np.var(matriz_2,0))
print(matriz_2m)
print(matriz_2sd)

[1.31623762e+02 2.46264026e+02 1.48514851e-01 1.49646865e+02]
[17.50917807 51.74515101  0.3556096  22.86733258]


In [7]:
matriz_normalizada= (matriz_2 - matriz_2m)/matriz_2sd
print(np.mean(matriz_normalizada, 0))
print(np.var(matriz_normalizada, 0))

[-7.03507659e-16 -1.11388713e-16 -2.34502553e-17 -6.80057404e-16]
[1. 1. 1. 1.]


In [8]:
matrizM=matriz_normalizada.T.dot(matriz_normalizada)
print(matrizM)

[[303.          37.32178458  53.79175421 -14.14941163]
 [ 37.32178458 303.           4.02796148  -3.01177111]
 [ 53.79175421   4.02796148 303.          -2.59583353]
 [-14.14941163  -3.01177111  -2.59583353 303.        ]]


In [9]:
matrizCov=matrizM/matrizM[0,0]
print(matrizCov)

[[ 1.          0.12317421  0.17753054 -0.04669773]
 [ 0.12317421  1.          0.0132936  -0.00993984]
 [ 0.17753054  0.0132936   1.         -0.00856711]
 [-0.04669773 -0.00993984 -0.00856711  1.        ]]


In [10]:
valores,vectores= np.linalg.eig(matrizCov)
print(valores)
print(vectores.T)

[1.23004268 0.78709002 0.99591063 0.98695667]
[[-0.69254251 -0.41121068 -0.56489849  0.17938878]
 [-0.71983337  0.37524636  0.57206681 -0.11734413]
 [-0.04548222  0.09574143 -0.31359091 -0.9436237 ]
 [-0.01249598  0.82518454 -0.5052623   0.25223864]]


In [11]:
vec_val_list=[[valores[i], vectores.T[i]] for i in range(4)]
vec_val_list.sort(reverse=True)
print(vec_val_list)

[[1.2300426771549615, array([-0.69254251, -0.41121068, -0.56489849,  0.17938878])], [0.9959106271557402, array([-0.04548222,  0.09574143, -0.31359091, -0.9436237 ])], [0.986956674599235, array([-0.01249598,  0.82518454, -0.5052623 ,  0.25223864])], [0.7870900210900623, array([-0.71983337,  0.37524636,  0.57206681, -0.11734413])]]


In [12]:
cambio_matriz=np.array([vec_val_list[i][1] for i in range(4)]).T
nueva_matriz=matriz_normalizada.dot(cambio_matriz)
print(nueva_matriz)

[[-1.77350885 -0.82473434 -1.42699298  0.72185725]
 [ 0.56348323 -1.39928559  0.68377637 -0.3367448 ]
 [ 0.81136666 -0.86541995 -0.21524758 -0.59335561]
 ...
 [-1.4866848  -0.52476043 -2.16343757  0.51908001]
 [ 0.94433489  1.35162487 -2.00812492 -0.8302417 ]
 [ 0.57275715 -0.88874225  0.31712032 -0.3715605 ]]


In [13]:
valores_2=list(100*valores/valores.sum())
valores_2.sort(reverse=True)
print(valores_2)

[30.75106692887405, 24.897765678893514, 24.67391686498088, 19.677250527251566]


In [14]:
matriz_reducida=nueva_matriz[:,[0,1,2]]
print(matriz_reducida)

[[-1.77350885e+00 -8.24734338e-01 -1.42699298e+00]
 [ 5.63483234e-01 -1.39928559e+00  6.83776369e-01]
 [ 8.11366661e-01 -8.65419951e-01 -2.15247584e-01]
 [ 9.99667340e-01 -1.02782660e+00  3.68379230e-01]
 [-5.57317700e-02 -1.90520054e-01  2.08467791e+00]
 [ 3.22923371e-01  7.67642167e-02 -6.78482033e-01]
 [-4.48430982e-01  5.91639523e-02  1.00327368e+00]
 [ 7.45878722e-01 -7.71544158e-01  7.43798022e-01]
 [-2.47711305e+00 -1.45296030e+00 -1.85609714e+00]
 [ 3.22080320e-01 -1.06651165e+00 -7.81555389e-01]
 [ 4.35588125e-02 -3.31455751e-01  2.03397439e-01]
 [-1.17364629e-02  6.27697404e-01  5.52988482e-01]
 [ 3.10817525e-01 -7.09439347e-01  7.62441424e-01]
 [ 1.32714769e+00  3.54908175e-01 -3.98198972e-01]
 [-2.27447951e+00 -1.24039167e+00 -5.00840647e-01]
 [ 9.77868460e-01 -2.33978020e-01 -1.23331752e-01]
 [ 1.26126915e-01 -5.87809813e-01  1.96069337e+00]
 [-6.09522398e-01  1.51671127e+00 -5.18455611e-01]
 [-3.29254701e-01 -7.96546523e-01  4.45173089e-01]
 [-2.70440459e-02  3.99305165e-